module DeviseTokenAuth::Concerns::UserOmniauthCallbacks
  extend ActiveSupport::Concern

  def uid_and_provider_defined?: () -> untyped

  def email_provider?: () -> untyped

  def sync_uid: () -> (nil | untyped)
end
