module DeviseTokenAuth
  class PasswordsController < DeviseTokenAuth::ApplicationController
    # this action is responsible for generating password reset tokens and sending emails
    def create: () { (untyped) -> untyped } -> untyped

    # this is where users arrive after visiting the password reset confirmation link
    def edit: () { (untyped) -> untyped } -> untyped

    def update: () { (untyped) -> untyped } -> untyped

    def resource_update_method: () -> untyped

    def render_create_error_missing_email: () -> untyped

    def render_create_error_missing_redirect_url: () -> untyped

    def render_error_not_allowed_redirect_url: () -> untyped

    def render_create_success: () -> untyped

    def render_create_error: (untyped errors) -> untyped

    def render_edit_error: () -> untyped

    def render_update_error_unauthorized: () -> untyped

    def render_update_error_password_not_required: () -> untyped

    def render_update_error_missing_password: () -> untyped

    def render_update_success: () -> untyped

    def render_update_error: () -> untyped

    private

    def resource_params: () -> untyped

    def password_resource_params: () -> untyped

    def render_not_found_error: () -> untyped

    def validate_redirect_url_param: () -> untyped

    def reset_password_token_as_raw?: (untyped recoverable) -> untyped

    def require_client_password_reset_token?: () -> untyped
  end
end
