# rails7でapiモード中にsessionを操作するとエラーになる現象の対処
# @see https://blog.furu07yu.com/entry/rails7-devise-token-auth#ActionDispatchRequestSessionDisabledSessionError%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
module DeviseHackFakeSession
  extend AbstractController::Callbacks::ClassMethods
  extend ActiveSupport::Concern

  class FakeSession < Hash[untyped, untyped]
    def enabled?: () -> false

    def destroy: () -> nil
  end

  private

  def set_fake_session: () -> (nil | untyped)
  def request: () -> untyped
end
