module Api
  module V1
    class ApplicationController < ::ApplicationController
      include DeviseTokenAuth::Concerns::SetUserByToken

      # 現在ログイン中のユーザーを、Manager型として返す。current_api_v1_userのエイリアス。
      def current_api_v1_manager: () -> ::Manager

      # 現在ログイン中のユーザーを、Client型として返す。current_api_v1_userのエイリアス。
      def current_api_v1_client: () -> ::Client

      private

      def render_user_type_mismatch: () -> untyped

      # 未ログインまたはクライアントではない場合、エラーレンダリングする
      def authenticate_api_v1_client!: () -> (nil | untyped)

      # 未ログインまたはケアマネではない場合、エラーレンダリングする
      def authenticate_api_v1_manager!: () -> (nil | untyped)
    end
  end
end

module DeviseTokenAuth
  module Concerns
    module SetUserByToken
      def authenticate_api_v1_user!: () -> untyped
      def current_api_v1_user: () -> ::User
    end
  end
end