module Devise
  class SecretKeyFinder
    def initialize: (untyped application) -> void

    def find: () -> (untyped | untyped | untyped | untyped | nil)

    private

    def key_exists?: (untyped object) -> untyped
  end
end
