module Devise
  module Models
    # Timeoutable takes care of verifying whether a user session has already
    # expired or not. When a session expires after the configured time, the user
    # will be asked for credentials again, it means, they will be redirected
    # to the sign in page.
    #
    # == Options
    #
    # Timeoutable adds the following options to +devise+:
    #
    #   * +timeout_in+: the interval to timeout the user session without activity.
    #
    # == Examples
    #
    #   user.timedout?(30.minutes.ago)
    #
    module Timeoutable
      extend ActiveSupport::Concern

      def self.required_fields: (untyped klass) -> ::Array[untyped]

      # Checks whether the user session has expired based on configured time.
      def timedout?: (untyped last_access) -> untyped

      def timeout_in: () -> untyped

      private

      module ClassMethods
      end
    end
  end
end
